spring.datasource.url=jdbc:postgresql://localhost:5435/course_management
spring.datasource.username=nguyentungduong
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true